#the purpose of this code is to create a bridge between ROS2 and Gazebo
#Specifically, it specifies which topics (and their data) need to be shared
#and translated between the two in order to get odometry to work

#topic 1: velocity; keyboard commands go into Gazebo
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ #ROS --> GZ

#topic 2: odometry: robot's belief about it's position comes out of Gazebo
- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS #GZ --> ROS

#topic 3: tf tree: information about relative position of odom and base_footprint frames comes out of Gazebo
- ros_topic_name: "/tf"
  gz_topic_name: "/model/gigi/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS #GZ --> 
  
# topic 4: data from LiDAR scans coming OUT of Gazebo, then shared with Ros
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  publisher_qos:
    reliability: best_effort
    durability: volatile
    history:
      kind: keep_last
      depth: 10

  # topic 5: joint states (wheel angles) coming OUT of Gazebo
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/gigi/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

  # simulation clock: Gazebo -> ROS, so simulated time in gazebo aligns with ros time
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS